# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wijn', '0011_docgdruif_kleur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vraag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubriek', models.CharField(max_length=255)),
                ('vraag', models.CharField(max_length=255)),
                ('goed', models.CharField(max_length=255)),
                ('afleider1', models.CharField(max_length=255)),
                ('afleider2', models.CharField(max_length=255, null=True)),
                ('afleider3', models.CharField(max_length=255, null=True)),
                ('afleider4', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
